//
//  HomeModels.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    enum RequestLocationPermission
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum SubscribContinuousLocation
    {
        struct Request {
            
        }
        
        struct Response {
            var locations: [Location]
            var error: Error?
        }
        
        struct ViewModel {
            var locations: [Location]
            var error: Error?
        }
    }
    
    enum RemoveAllLocations
    {
        struct Request {
            
        }
        
        struct Response {
            var removedCount: Int
        }
        
        struct ViewModel {
            var removedCount: Int
        }
    }
}
