//
//  HomePresenter.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentRequestLocation(response: Home.RequestLocationPermission.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentRequestLocation(response: Home.RequestLocationPermission.Response)
    {
        let viewModel = Home.RequestLocationPermission.ViewModel()
        viewController?.displayLocationPermission(viewModel: viewModel)
    }
}
