//
//  HomeInteractor.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func requestLocationPermission(request: Home.RequestLocationPermission.Request)
    func subscribLocation(request: Home.SubscribContinuousLocation.Request)
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func requestLocationPermission(request: Home.RequestLocationPermission.Request)
    {
        worker = HomeWorker()
        worker?.requestPermission()
        
        let response = Home.RequestLocationPermission.Response()
        presenter?.presentRequestLocation(response: response)
    }
    
    func subscribLocation(request: Home.SubscribContinuousLocation.Request)
    {
        worker?.subscribeContinuousLocation(onUpdate: { (location) in
            
        }, onFail: { (error, location) in
            
        })
    }
}
