//
//  HomePresenter.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentRequestLocation(response: Home.RequestLocationPermission.Response)
    func presentContinuousLocationUpdate(response: Home.SubscribContinuousLocation.Response)
    func presentRemoveAllLocations(response: Home.RemoveAllLocations.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentRequestLocation(response: Home.RequestLocationPermission.Response)
    {
        let viewModel = Home.RequestLocationPermission.ViewModel()
        viewController?.displayLocationPermission(viewModel: viewModel)
    }
    
    func presentContinuousLocationUpdate(response: Home.SubscribContinuousLocation.Response)
    {
        let viewModel = Home.SubscribContinuousLocation.ViewModel(locations: response.locations, error: response.error)
        viewController?.displayContinuousLocationUpdate(viewModel: viewModel)
    }
    
    func presentRemoveAllLocations(response: Home.RemoveAllLocations.Response)
    {
        let viewModel = Home.RemoveAllLocations.ViewModel(removedCount: response.removedCount)
        viewController?.displayRemoveAllLocations(viewModel: viewModel)
    }
}
