//
//  HomeWorker.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import SwiftLocation
import CoreLocation

typealias locationUpdateHandler = (CLLocation) -> Void
typealias locationErrorHandler = (LocationError, CLLocation?) -> Void

class HomeWorker
{
    func requestPermission()
    {
        Locator.requestAuthorizationIfNeeded(.always)
    }
    
    func subscribeContinuousLocation(onUpdate: @escaping locationUpdateHandler,
                                     onFail: @escaping locationErrorHandler)
    {
        Locator.subscribeSignificantLocations(onUpdate: onUpdate, onFail: onFail)
    }
    
}
