//
//  FaceDetectionPresenter.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FaceDetectionPresentationLogic
{
    func presentSomething(response: FaceDetection.SetUpFaceCaptureSession.Response)
    func presentVision(response: FaceDetection.PrepareVision.Response)
}

class FaceDetectionPresenter: FaceDetectionPresentationLogic
{
    weak var viewController: FaceDetectionDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: FaceDetection.SetUpFaceCaptureSession.Response)
    {
        let viewModel = FaceDetection.SetUpFaceCaptureSession.ViewModel(rootLayer: response.rootLayer, error: response.error)
        viewController?.displayCapture(viewModel: viewModel)
    }
    
    func presentVision(response: FaceDetection.PrepareVision.Response)
    {
        let viewModel = FaceDetection.PrepareVision.ViewModel(detectionOverlayLayer: response.detectionOverlayLayer,
                                                              detectedFaceRectangleShapeLayer: response.detectedFaceRectangleShapeLayer,
                                                              detectedFaceLandmarksShapeLayer: response.detectedFaceLandmarksShapeLayer)
        viewController?.displayPrepareVision(viewModel: viewModel)
    }
}
