//
//  FaceDetectionModels.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FaceDetection
{
    // MARK: Use cases
    
    enum SetUpFaceCaptureSession
    {
        struct Request
        {
            var preview: UIView
        }
        struct Response
        {
            var rootLayer: CALayer?
            var error: DataError?
        }
        struct ViewModel
        {
            var rootLayer: CALayer?
            var error: DataError?
        }
    }
    
    enum PrepareVision
    {
        struct Request {
            
        }
        
        struct Response {
            var detectionOverlayLayer: CALayer?
            var detectedFaceRectangleShapeLayer: CAShapeLayer?
            var detectedFaceLandmarksShapeLayer: CAShapeLayer?
        }
        
        struct ViewModel {
            var detectionOverlayLayer: CALayer?
            var detectedFaceRectangleShapeLayer: CAShapeLayer?
            var detectedFaceLandmarksShapeLayer: CAShapeLayer?
        }
    }
    
    enum startFaceCaptureAndDetection
    {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum stopFaceCaptureAndDection
    {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
