platform :ios, '11.0'

target 'FaceGPS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLocation', '~> 3.2.3'
  pod 'RealmSwift'

  target 'FaceGPSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
