//
//  FaceDetectionInteractor.swift
//  FaceGPS
//
//  Created by Zhenjiang Liu on 2018-09-08.
//  Copyright (c) 2018 zhenjiang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FaceDetectionBusinessLogic
{
    func setupCapture(request: FaceDetection.SetUpFaceCaptureSession.Request)
    func setupVision(request: FaceDetection.PrepareVision.Request)
    func startCapture(request: FaceDetection.startFaceCaptureAndDetection.Request)
}

protocol FaceDetectionDataStore
{
    //var name: String { get set }
}

class FaceDetectionInteractor: FaceDetectionBusinessLogic, FaceDetectionDataStore
{
    var presenter: FaceDetectionPresentationLogic?
    var worker: FaceDetectionWorker?
    
    // MARK: Do something
    
    func setupCapture(request: FaceDetection.SetUpFaceCaptureSession.Request)
    {
        worker = FaceDetectionWorker()
        let result = worker?.setupAVCaptureSession(preview: request.preview)
        
        let response = FaceDetection.SetUpFaceCaptureSession.Response(rootLayer: result?.0, error: result?.1)
        presenter?.presentSomething(response: response)
    }
    
    func setupVision(request: FaceDetection.PrepareVision.Request)
    {
        if let worker = worker {
            let result = worker.prepareVisionRequest()
            let response = FaceDetection.PrepareVision.Response(detectionOverlayLayer: result.0, detectedFaceRectangleShapeLayer: result.1, detectedFaceLandmarksShapeLayer: result.2)
            presenter?.presentVision(response: response)
        }
    }
    
    func startCapture(request: FaceDetection.startFaceCaptureAndDetection.Request)
    {
        worker?.startCaptureFace()
    }
}
